Title: '§3[§6§l分解系统§3]'  #分解Gui标题
确定分解: '§c确认分解'  #确认分解按钮显示
data:
  分解1:  #随便填，仅做间隔标识
    lore: #判断lore，需与物品lore相符。颜色符号用“ § ”代替" & "

      - 'lore1'
      - 'lore2'
    数量: 1 #分解所需的数量
    分解几率: 2   #分解成功几率  1-100
    成功指令:
      - 'say 1'   #指令 %player% 代替玩家
      - 'say 1'
    失败指令:
      - 'say 2'
      - 'say 2'
  分解2:
    lore:
      - 'lore3'
      - 'lore4'
    数量: 1
    分解几率: 2
    成功指令:
      - 'say 3'
      - 'say 3'
    失败指令:
      - 'say 4'
      - 'say 4'